#!/data/data/com.termux/files/usr/bin/bash
set -u -o pipefail

# Zip_Bug controlled Termux Android build workflow.
# This script never creates or modifies signing credentials.

MODE="debug"
EXPORT_PATH=""
CANCEL_FILE=""
TIMEOUT_SECONDS=1200

stage() {
  printf 'ZIPBUG_STAGE|%s|%s|%s\n' "$1" "$2" "$3"
}

fail_stage() {
  local stage_name="$1"
  local message="$2"
  local code="${3:-1}"
  stage "$stage_name" "FAIL" "$message"
  printf 'ZIPBUG_RESULT|FAILED|%s\n' "$message"
  exit "$code"
}

usage() {
  cat <<'EOF'
Usage:
  scripts/build-termux.sh --debug [--export PATH] [--cancel-file PATH] [--timeout-seconds N]
  scripts/build-termux.sh --release

Release signing is intentionally not configured or generated by Zip_Bug.
Configure project signing explicitly outside this script before adding a controlled release workflow.
EOF
}

while [ "$#" -gt 0 ]; do
  case "$1" in
    --debug)
      MODE="debug"
      shift
      ;;
    --release)
      MODE="release"
      shift
      ;;
    --export)
      [ "$#" -ge 2 ] || fail_stage "VALIDATION" "--export requires a path" 2
      EXPORT_PATH="$2"
      shift 2
      ;;
    --cancel-file)
      [ "$#" -ge 2 ] || fail_stage "VALIDATION" "--cancel-file requires a path" 2
      CANCEL_FILE="$2"
      shift 2
      ;;
    --timeout-seconds)
      [ "$#" -ge 2 ] || fail_stage "VALIDATION" "--timeout-seconds requires a value" 2
      TIMEOUT_SECONDS="$2"
      shift 2
      ;;
    --help|-h)
      usage
      exit 0
      ;;
    *)
      fail_stage "VALIDATION" "Unknown build option: $1" 2
      ;;
  esac
done

if [ "$MODE" = "release" ]; then
  stage "SIGNING" "BLOCKED" "Release signing requires explicit project-managed credentials."
  printf '%s\n' "Zip_Bug will not create, overwrite, or guess release signing credentials."
  printf '%s\n' "Use a separately configured release signing workflow after reviewing the keystore and Gradle signingConfig."
  exit 3
fi

case "$TIMEOUT_SECONDS" in
  ''|*[!0-9]*)
    fail_stage "VALIDATION" "Timeout must be an integer number of seconds." 2
    ;;
esac

if [ "$TIMEOUT_SECONDS" -lt 60 ] || [ "$TIMEOUT_SECONDS" -gt 3600 ]; then
  fail_stage "VALIDATION" "Timeout must be between 60 and 3600 seconds." 2
fi

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$PROJECT_ROOT"

stage "VALIDATION" "RUNNING" "Checking Android project structure."

if [ ! -f "settings.gradle.kts" ] && [ ! -f "settings.gradle" ]; then
  fail_stage "VALIDATION" "Missing settings.gradle.kts/settings.gradle in $PROJECT_ROOT" 2
fi

if [ ! -f "app/build.gradle.kts" ] && [ ! -f "app/build.gradle" ]; then
  fail_stage "VALIDATION" "Missing app/build.gradle.kts/app/build.gradle in $PROJECT_ROOT" 2
fi

if [ -n "$CANCEL_FILE" ]; then
  case "$CANCEL_FILE" in
    "$PROJECT_ROOT"/*) ;;
    *)
      fail_stage "VALIDATION" "Cancel file must stay inside the project root." 2
      ;;
  esac
fi

if [ -z "$EXPORT_PATH" ]; then
  EXPORT_PATH="/storage/emulated/0/Download/Zip_Bug-debug.apk"
fi

case "$EXPORT_PATH" in
  /storage/emulated/0/*|/data/data/com.termux/files/home/storage/*) ;;
  *)
    fail_stage "VALIDATION" "APK export path must be shared storage." 2
    ;;
esac

stage "VALIDATION" "PASS" "Project root: $PROJECT_ROOT"

stage "DEPENDENCIES" "RUNNING" "Checking Java, Gradle, Android SDK, and aapt2."

if [ -z "${ANDROID_HOME:-}" ]; then
  if [ -d "$HOME/android-sdk" ]; then
    export ANDROID_HOME="$HOME/android-sdk"
    export ANDROID_SDK_ROOT="$ANDROID_HOME"
  else
    fail_stage "DEPENDENCIES" "ANDROID_HOME is not set and $HOME/android-sdk was not found." 4
  fi
fi

if [ ! -f "$ANDROID_HOME/platforms/android-34/android.jar" ]; then
  fail_stage "DEPENDENCIES" "Android SDK 34 is missing: $ANDROID_HOME/platforms/android-34/android.jar" 4
fi

if ! command -v java >/dev/null 2>&1; then
  fail_stage "DEPENDENCIES" "Java is not installed in Termux." 4
fi

JAVA_LINE="$(java -version 2>&1 | head -n 1 || true)"
printf 'ZIPBUG_DEP|JAVA|%s\n' "$JAVA_LINE"

if [ -x "./gradlew" ]; then
  BUILD_CMD="./gradlew"
elif command -v gradle >/dev/null 2>&1; then
  BUILD_CMD="$(command -v gradle)"
else
  fail_stage "DEPENDENCIES" "Neither ./gradlew nor Termux gradle is available." 4
fi

AAPT2_PATH="$(command -v aapt2 2>/dev/null || true)"
if [ -z "$AAPT2_PATH" ]; then
  fail_stage "DEPENDENCIES" "Native Termux aapt2 is missing. Install it before building." 4
fi

mkdir -p "$HOME/.gradle"
GRADLE_PROPS="$HOME/.gradle/gradle.properties"
if grep -q '^android.aapt2FromMavenOverride=' "$GRADLE_PROPS" 2>/dev/null; then
  CURRENT_AAPT2="$(grep '^android.aapt2FromMavenOverride=' "$GRADLE_PROPS" | tail -n 1 | cut -d= -f2-)"
  if [ "$CURRENT_AAPT2" != "$AAPT2_PATH" ]; then
    stage "DEPENDENCIES" "WARN" "Existing aapt2 override differs; it was not overwritten."
    printf 'ZIPBUG_DEP|AAPT2_EXPECTED|%s\n' "$AAPT2_PATH"
    printf 'ZIPBUG_DEP|AAPT2_CONFIGURED|%s\n' "$CURRENT_AAPT2"
  fi
else
  printf 'android.aapt2FromMavenOverride=%s\n' "$AAPT2_PATH" >> "$GRADLE_PROPS"
  printf 'ZIPBUG_DEP|AAPT2_CONFIGURED|%s\n' "$AAPT2_PATH"
fi

stage "DEPENDENCIES" "PASS" "Required debug-build dependencies are available."

stage "BUILD" "RUNNING" "Gradle clean assembleDebug started."

"$BUILD_CMD" --no-daemon clean assembleDebug &
BUILD_PID=$!
BUILD_STARTED="$(date +%s)"

terminate_build() {
  local reason="$1"
  if kill -0 "$BUILD_PID" 2>/dev/null; then
    kill -TERM "$BUILD_PID" 2>/dev/null || true
    sleep 2
    if kill -0 "$BUILD_PID" 2>/dev/null; then
      kill -KILL "$BUILD_PID" 2>/dev/null || true
    fi
  fi
  wait "$BUILD_PID" 2>/dev/null || true
  printf 'ZIPBUG_RESULT|%s|%s\n' "$reason" "$reason"
}

while kill -0 "$BUILD_PID" 2>/dev/null; do
  if [ -n "$CANCEL_FILE" ] && [ -f "$CANCEL_FILE" ]; then
    stage "BUILD" "CANCELLED" "Cancellation requested by Zip_Bug."
    terminate_build "CANCELLED"
    rm -f "$CANCEL_FILE" 2>/dev/null || true
    exit 130
  fi

  NOW="$(date +%s)"
  ELAPSED=$((NOW - BUILD_STARTED))
  if [ "$ELAPSED" -ge "$TIMEOUT_SECONDS" ]; then
    stage "BUILD" "TIMEOUT" "Build exceeded ${TIMEOUT_SECONDS}s."
    terminate_build "TIMEOUT"
    exit 124
  fi

  sleep 1
done

wait "$BUILD_PID"
BUILD_EXIT=$?

if [ "$BUILD_EXIT" -ne 0 ]; then
  fail_stage "BUILD" "Gradle failed with exit code $BUILD_EXIT." "$BUILD_EXIT"
fi

stage "BUILD" "PASS" "Gradle assembleDebug exited 0."

stage "PACKAGING" "RUNNING" "Validating APK and exporting artifact."

APK_OUTPUT="app/build/outputs/apk/debug/app-debug.apk"

if [ ! -f "$APK_OUTPUT" ]; then
  fail_stage "PACKAGING" "Gradle exited 0 but APK was not found at $APK_OUTPUT" 5
fi

APK_SIZE="$(wc -c < "$APK_OUTPUT" | tr -d ' ')"
if [ -z "$APK_SIZE" ] || [ "$APK_SIZE" -le 0 ]; then
  fail_stage "PACKAGING" "APK exists but has zero/invalid size." 5
fi

if ! "$AAPT2_PATH" dump badging "$APK_OUTPUT" >/dev/null 2>&1; then
  fail_stage "PACKAGING" "aapt2 could not parse the generated APK." 5
fi

SIGNATURE_VERIFY="NOT_AVAILABLE"
if command -v apksigner >/dev/null 2>&1; then
  if ! apksigner verify "$APK_OUTPUT" >/dev/null 2>&1; then
    fail_stage "PACKAGING" "apksigner verification failed." 5
  fi
  SIGNATURE_VERIFY="PASS"
fi

APK_SHA="$(sha256sum "$APK_OUTPUT" | cut -d' ' -f1)"

mkdir -p "$(dirname "$EXPORT_PATH")"
cp -f "$APK_OUTPUT" "$EXPORT_PATH"

if [ ! -f "$EXPORT_PATH" ]; then
  fail_stage "PACKAGING" "APK copy did not produce the requested export file." 5
fi

EXPORTED_SIZE="$(wc -c < "$EXPORT_PATH" | tr -d ' ')"
EXPORTED_SHA="$(sha256sum "$EXPORT_PATH" | cut -d' ' -f1)"

if [ "$EXPORTED_SIZE" != "$APK_SIZE" ] || [ "$EXPORTED_SHA" != "$APK_SHA" ]; then
  fail_stage "PACKAGING" "Exported APK does not match the built artifact." 5
fi

printf 'ZIPBUG_ARTIFACT|%s|%s|%s|%s\n' "$EXPORT_PATH" "$EXPORTED_SIZE" "$EXPORTED_SHA" "$SIGNATURE_VERIFY"
stage "PACKAGING" "PASS" "APK validated and exported."
printf 'ZIPBUG_RESULT|SUCCESS|debug\n'
exit 0
