package com.zipbug.base.creator

data class AppSpec(
    val name: String,
    val packageName: String,
    val goal: String
)

object AppScaffolder {
    private val packageRegex =
        Regex("^[a-zA-Z][a-zA-Z0-9_]*(\\.[a-zA-Z][a-zA-Z0-9_]*)+$")

    fun validate(spec: AppSpec) {
        require(spec.name.isNotBlank()) { "App name is required" }
        require(spec.name.length <= 60) { "App name is too long" }
        require(packageRegex.matches(spec.packageName)) {
            "Invalid package name"
        }
        require(spec.goal.length <= 4000) { "Goal is too long" }
    }

    fun files(spec: AppSpec): Map<String, String> {
        validate(spec)

        val packagePath = spec.packageName.replace('.', '/')
        val safeGoal = spec.goal
            .replace("*/", "* /")
            .ifBlank { "Generated by Zip_Bug App Creator" }

        return linkedMapOf(
            "settings.gradle.kts" to settingsGradle(spec.name),
            "build.gradle.kts" to rootGradle(),
            "gradle.properties" to gradleProperties(),
            "app/build.gradle.kts" to appGradle(spec.packageName),
            "app/proguard-rules.pro" to "# Add project-specific rules here.\n",
            "app/src/main/AndroidManifest.xml" to manifest(),
            "app/src/main/java/" + packagePath + "/MainActivity.kt" to
                mainActivity(spec.packageName, safeGoal),
            "app/src/main/res/layout/activity_main.xml" to mainLayout(spec.name),
            "app/src/main/res/values/strings.xml" to strings(spec.name),
            "app/src/main/res/values/colors.xml" to colors(),
            "app/src/main/res/values/themes.xml" to themes(),
            "README.md" to readme(spec)
        )
    }

    private fun settingsGradle(name: String) = """
        pluginManagement {
            repositories { google(); mavenCentral(); gradlePluginPortal() }
        }
        dependencyResolutionManagement {
            repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
            repositories { google(); mavenCentral() }
        }
        rootProject.name = __PROJECT_NAME__
        include(":app")
    """.trimIndent()
        .replace("__PROJECT_NAME__", quote(name)) + "\n"

    private fun rootGradle() = """
        plugins {
            id("com.android.application") version "8.7.3" apply false
            id("org.jetbrains.kotlin.android") version "1.9.24" apply false
        }
    """.trimIndent() + "\n"

    private fun gradleProperties() = """
        org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
        android.useAndroidX=true
        kotlin.code.style=official
        android.nonTransitiveRClass=true
    """.trimIndent() + "\n"

    private fun appGradle(packageName: String) = """
        plugins {
            id("com.android.application")
            id("org.jetbrains.kotlin.android")
        }

        android {
            namespace = "__PACKAGE__"
            compileSdk = 34

            defaultConfig {
                applicationId = "__PACKAGE__"
                minSdk = 24
                targetSdk = 34
                versionCode = 1
                versionName = "1.0.0"
            }

            compileOptions {
                sourceCompatibility = JavaVersion.VERSION_17
                targetCompatibility = JavaVersion.VERSION_17
            }
            kotlinOptions { jvmTarget = "17" }
        }

        dependencies {
            implementation("androidx.core:core-ktx:1.13.1")
            implementation("androidx.appcompat:appcompat:1.7.0")
            implementation("com.google.android.material:material:1.12.0")
        }
    """.trimIndent()
        .replace("__PACKAGE__", packageName) + "\n"

    private fun manifest() = """
        <manifest xmlns:android="http://schemas.android.com/apk/res/android">
            <application
                android:allowBackup="true"
                android:label="@string/app_name"
                android:theme="@style/Theme.Generated">
                <activity
                    android:name=".MainActivity"
                    android:exported="true">
                    <intent-filter>
                        <action android:name="android.intent.action.MAIN" />
                        <category android:name="android.intent.category.LAUNCHER" />
                    </intent-filter>
                </activity>
            </application>
        </manifest>
    """.trimIndent() + "\n"

    private fun mainActivity(
        packageName: String,
        goal: String
    ) = """
        package __PACKAGE__

        import android.os.Bundle
        import androidx.appcompat.app.AppCompatActivity

        /**
         * Project goal:
         * __GOAL__
         */
        class MainActivity : AppCompatActivity() {
            override fun onCreate(savedInstanceState: Bundle?) {
                super.onCreate(savedInstanceState)
                setContentView(R.layout.activity_main)
            }
        }
    """.trimIndent()
        .replace("__PACKAGE__", packageName)
        .replace("__GOAL__", goal) + "\n"

    private fun mainLayout(name: String) = """
        <LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:orientation="vertical"
            android:gravity="center"
            android:padding="24dp"
            android:background="@color/background">

            <TextView
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:text=__APP_NAME_QUOTED__
                android:textColor="@color/text_primary"
                android:textSize="30sp"
                android:textStyle="bold" />

            <TextView
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_marginTop="10dp"
                android:text="Created with Zip_Bug Antigravity Studio"
                android:textColor="@color/text_secondary"
                android:textSize="16sp" />

            <Button
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_marginTop="24dp"
                android:text="Start building" />
        </LinearLayout>
    """.trimIndent()
        .replace("__APP_NAME_QUOTED__", xmlQuote(name)) + "\n"

    private fun strings(name: String) = """
        <resources>
            <string name="app_name">__APP_NAME__</string>
        </resources>
    """.trimIndent()
        .replace("__APP_NAME__", xml(name)) + "\n"

    private fun colors() = """
        <resources>
            <color name="primary">#FF6B00</color>
            <color name="background">#121212</color>
            <color name="text_primary">#F7F3EF</color>
            <color name="text_secondary">#A9A29D</color>
        </resources>
    """.trimIndent() + "\n"

    private fun themes() = """
        <resources>
            <style name="Theme.Generated" parent="Theme.Material3.DayNight.NoActionBar">
                <item name="colorPrimary">@color/primary</item>
                <item name="android:statusBarColor">@color/background</item>
                <item name="android:navigationBarColor">@color/background</item>
            </style>
        </resources>
    """.trimIndent() + "\n"

    private fun readme(spec: AppSpec) = buildString {
        append("# ")
        append(spec.name)
        append("\n\nPackage: `")
        append(spec.packageName)
        append("`\n\n## Goal\n")
        append(spec.goal.ifBlank { "No goal supplied." })
        append("\n\n## Build\n")
        append("Java 17, Gradle 8.9 and Android SDK 34 are expected.\n\n")
        append("In Zip_Bug / Termux:\n")
        append("`/apkbuilder /path/to/this/project`\n\n")
        append("Generated by Zip_Bug Antigravity Studio.\n")
    }

    private fun quote(value: String): String =
        "\"" + value.replace("\\", "\\\\").replace("\"", "\\\"") + "\""

    private fun xml(value: String): String =
        value.replace("&", "&amp;")
            .replace("<", "&lt;")
            .replace(">", "&gt;")
            .replace("\"", "&quot;")
            .replace("'", "&apos;")

    private fun xmlQuote(value: String): String =
        "\"" + xml(value) + "\""
}
