package com.zipbug.base.creator

import org.json.JSONObject

object WebMiniAppScaffolder {
    fun files(
        name: String,
        goal: String
    ): Map<String, String> {
        require(name.isNotBlank()) { "App name is required" }
        require(name.length <= 60) { "App name is too long" }
        require(goal.length <= 4000) { "Goal is too long" }

        val slug = name.lowercase()
            .replace(Regex("[^a-z0-9]+"), "-")
            .trim('-')
            .ifBlank { "zipbug-app" }

        val manifest = JSONObject()
            .put("name", name)
            .put("slug", slug)
            .put("version", "1.0.0")
            .put("kind", "web-mini-app")
            .put("entry", "www/index.html")
            .put("permissions", org.json.JSONArray())
            .put("requiredTools", org.json.JSONArray())
            .toString(2) + "\n"

        val index = """
            <!doctype html>
            <html lang="en">
            <head>
              <meta charset="utf-8">
              <meta name="viewport" content="width=device-width,initial-scale=1">
              <meta name="theme-color" content="#121212">
              <title>__TITLE__</title>
              <link rel="stylesheet" href="style.css">
            </head>
            <body>
              <main class="shell">
                <div class="badge">ZIP_BUG MINI APP</div>
                <h1>__TITLE__</h1>
                <p id="goal">__GOAL__</p>
                <button id="action">Start</button>
                <pre id="output">Ready.</pre>
              </main>
              <script src="app.js"></script>
            </body>
            </html>
        """.trimIndent()
            .replace("__TITLE__", html(name))
            .replace(
                "__GOAL__",
                html(
                    goal.ifBlank {
                        "Generated by Zip_Bug Antigravity Studio."
                    }
                )
            ) + "\n"

        val css = """
            :root {
              color-scheme: dark;
              font-family: Inter, system-ui, sans-serif;
              background: #121212;
              color: #f7f3ef;
            }
            * { box-sizing: border-box; }
            body { margin: 0; min-height: 100vh; display: grid; place-items: center; }
            .shell {
              width: min(92vw, 620px);
              padding: 28px;
              border: 1px solid #35312f;
              border-radius: 24px;
              background: #1b1b1b;
            }
            .badge { color: #39d98a; font: 700 12px monospace; }
            h1 { font-size: 36px; margin: 12px 0; }
            p { color: #b8b0aa; line-height: 1.6; }
            button {
              width: 100%;
              border: 0;
              border-radius: 14px;
              padding: 14px 18px;
              background: #ff6b00;
              color: #121212;
              font-weight: 800;
            }
            pre {
              min-height: 80px;
              padding: 14px;
              border-radius: 14px;
              background: #101010;
              color: #39d98a;
              white-space: pre-wrap;
            }
        """.trimIndent() + "\n"

        val js = """
            const output = document.querySelector('#output');
            document.querySelector('#action').addEventListener('click', () => {
              const now = new Date().toISOString();
              output.textContent = 'Real local mini-app event at ' + now;
            });
        """.trimIndent() + "\n"

        return linkedMapOf(
            "app.json" to manifest,
            "www/index.html" to index,
            "www/style.css" to css,
            "www/app.js" to js
        )
    }

    private fun html(value: String): String =
        value.replace("&", "&amp;")
            .replace("<", "&lt;")
            .replace(">", "&gt;")
            .replace("\"", "&quot;")
            .replace("'", "&#39;")
}
